name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 16
      - uses: actions/setup-python@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: golang:1.17
        run: |
          go get
          gofmt -d -s .
          go test -cover -failfast -timeout 2s ./...
